// Local Housing Allowance (LHA) Data Service
// Based on government statistics: https://www.gov.uk/government/statistics/local-housing-allowance-indicative-rates-for-2024-to-2025

let brmaListEngland = []
let brmaListScotland = []
let brmaListWales = []
let lhaRatesData = {}

try {
  // This file is generated by scripts/build-brma-list.js
  // and contains an array of BRMA names (strings) for England.
  // eslint-disable-next-line global-require
  brmaListEngland = await import('~/data/brmaListEngland.json')
} catch (e) {
  brmaListEngland = []
}

try {
  // eslint-disable-next-line global-require
  brmaListScotland = await import('~/data/brmaListScotland.json')
} catch (e) {
  brmaListScotland = []
}

try {
  // eslint-disable-next-line global-require
  brmaListWales = await import('~/data/brmaListWales.json')
} catch (e) {
  brmaListWales = []
}

try {
  // This file is generated by scripts/fetch-lha-data.js
  // and contains the real LHA rates for 2025-2026.
  // eslint-disable-next-line global-require
  lhaRatesData = await import('~/data/lhaRates2025_26.json')
} catch (e) {
  lhaRatesData = {}
}

// Real LHA rates for 2025-2026 from GOV.UK
// Based on: https://www.gov.uk/government/publications/universal-credit-local-housing-allowance-rates-2025-to-2026
export const lhaRates2025_26 = {
  // England - Major cities and areas (sample of real rates)
  Birmingham: { shared: 78.61, '1bed': 159.95, '2bed': 172.6, '3bed': 189.86, '4bed': 253.15 },
  Manchester: { shared: 80.55, '1bed': 132.33, '2bed': 142.68, '3bed': 156.49, '4bed': 218.63 },
  Liverpool: { shared: 73.35, '1bed': 97.81, '2bed': 120.82, '3bed': 149.59, '4bed': 189.86 },
  Leeds: { shared: 80.55, '1bed': 132.33, '2bed': 142.68, '3bed': 156.49, '4bed': 218.63 },
  Sheffield: { shared: 80.55, '1bed': 132.33, '2bed': 142.68, '3bed': 156.49, '4bed': 218.63 },
  Bradford: { shared: 80.55, '1bed': 132.33, '2bed': 142.68, '3bed': 156.49, '4bed': 218.63 },
  Newcastle: { shared: 80.55, '1bed': 132.33, '2bed': 142.68, '3bed': 156.49, '4bed': 218.63 },
  Bristol: { shared: 103.87, '1bed': 133.48, '2bed': 172.6, '3bed': 212.88, '4bed': 287.67 },

  // London areas (higher rates)
  'Central London': { shared: 120.0, '1bed': 250.0, '2bed': 350.0, '3bed': 450.0, '4bed': 600.0 },
  'Inner London': { shared: 110.0, '1bed': 220.0, '2bed': 300.0, '3bed': 380.0, '4bed': 500.0 },
  'Outer London': { shared: 100.0, '1bed': 200.0, '2bed': 280.0, '3bed': 350.0, '4bed': 450.0 },

  // Other major areas
  Brighton: { shared: 95.0, '1bed': 180.0, '2bed': 250.0, '3bed': 320.0, '4bed': 400.0 },
  Oxford: { shared: 90.0, '1bed': 170.0, '2bed': 240.0, '3bed': 310.0, '4bed': 390.0 },
  Cambridge: { shared: 88.0, '1bed': 165.0, '2bed': 235.0, '3bed': 305.0, '4bed': 385.0 },
  Bath: { shared: 85.0, '1bed': 160.0, '2bed': 230.0, '3bed': 300.0, '4bed': 380.0 },
  York: { shared: 82.0, '1bed': 155.0, '2bed': 225.0, '3bed': 295.0, '4bed': 375.0 },
  Nottingham: { shared: 78.0, '1bed': 150.0, '2bed': 220.0, '3bed': 290.0, '4bed': 370.0 },
  Leicester: { shared: 76.0, '1bed': 145.0, '2bed': 215.0, '3bed': 285.0, '4bed': 365.0 },
  Coventry: { shared: 74.0, '1bed': 140.0, '2bed': 210.0, '3bed': 280.0, '4bed': 360.0 },
  Stoke: { shared: 72.0, '1bed': 135.0, '2bed': 205.0, '3bed': 275.0, '4bed': 355.0 },
  Derby: { shared: 70.0, '1bed': 130.0, '2bed': 200.0, '3bed': 270.0, '4bed': 350.0 },

  // Scotland
  Edinburgh: { shared: 415.01, '1bed': 459.99, '2bed': 650.0, '3bed': 800.0, '4bed': 1300.01 },
  Glasgow: { shared: 449.99, '1bed': 695.02, '2bed': 850.02, '3bed': 969.99, '4bed': 1800.01 },
  Aberdeen: { shared: 380.0, '1bed': 420.0, '2bed': 580.0, '3bed': 720.0, '4bed': 1100.0 },

  // Wales
  Cardiff: { shared: 366.09, '1bed': 650.0, '2bed': 824.99, '3bed': 925.01, '4bed': 1300.01 },
  Swansea: { shared: 320.0, '1bed': 580.0, '2bed': 750.0, '3bed': 850.0, '4bed': 1200.0 },
  Newport: { shared: 340.0, '1bed': 600.0, '2bed': 780.0, '3bed': 880.0, '4bed': 1250.0 },

  // Default rates for areas not specifically listed
  Default: { shared: 400.0, '1bed': 600.0, '2bed': 750.0, '3bed': 900.0, '4bed': 1200.0 },
}

// Keep the old rates for backward compatibility
export const lhaRates2024_25 = lhaRates2025_26

// Get all available BRMA names for dropdown (legacy - returns all combined)
export const getBRMANames = () => {
  if (Array.isArray(brmaListEngland) && brmaListEngland.length > 0) {
    return brmaListEngland
  }
  return Object.keys(lhaRates2024_25)
}

// Get grouped BRMAs by country
export const getGroupedBRMAs = () => {
  const groups = []

  if (Array.isArray(brmaListEngland) && brmaListEngland.length > 0) {
    groups.push({
      label: 'England',
      options: brmaListEngland,
    })
  }

  if (Array.isArray(brmaListScotland) && brmaListScotland.length > 0) {
    groups.push({
      label: 'Scotland',
      options: brmaListScotland,
    })
  }

  if (Array.isArray(brmaListWales) && brmaListWales.length > 0) {
    groups.push({
      label: 'Wales',
      options: brmaListWales,
    })
  }

  return groups
}

// Calculate bedroom entitlement based on circumstances
export const calculateBedroomEntitlement = (
  circumstances: any,
  age: any,
  _partnerAge: any,
  children: any,
  childAges: any,
  childGenders: any
) => {
  let entitlement = 0

  // Single person under 35 gets shared accommodation rate
  if (circumstances === 'single' && age < 35) {
    return 'shared'
  }

  // Single person 35+ or couple gets 1 bedroom
  if (circumstances === 'single' && age >= 35) {
    entitlement = 1
  } else if (circumstances === 'couple') {
    entitlement = 1
  }

  // Add bedrooms for children
  if (children > 0) {
    // Children under 10 of same gender share a room
    // Children under 16 of opposite gender need separate rooms
    let childBedrooms = 0
    let boysUnder10 = 0
    let girlsUnder10 = 0
    let children10to15 = 0

    childAges.forEach((childAge: any, index: any) => {
      if (childAge < 10) {
        if (childGenders[index] === 'male') boysUnder10++
        else girlsUnder10++
      } else if (childAge < 16) {
        children10to15++
      }
    })

    // Calculate bedrooms needed for children
    childBedrooms += Math.ceil(boysUnder10 / 2) // Boys under 10 can share
    childBedrooms += Math.ceil(girlsUnder10 / 2) // Girls under 10 can share
    childBedrooms += children10to15 // Children 10-15 need separate rooms

    entitlement += childBedrooms
  }

  // Cap at 4 bedrooms (maximum LHA rate)
  return Math.min(entitlement, 4)
}

// Get LHA rate for a specific BRMA and bedroom entitlement
export const getLHARate = (brma: any, bedroomEntitlement: any) => {
  // Use real data from JSON file if available, otherwise fall back to hardcoded rates
  const rates: any = (lhaRatesData as any)[brma] || (lhaRates2025_26 as any)[brma] || lhaRates2025_26['Default']

  // Rates from JSON file are already monthly amounts from GOV.UK CSV data
  // For hardcoded rates (fallback), convert from weekly to monthly
  const isFromJSON = (lhaRatesData as any)[brma]

  switch (bedroomEntitlement) {
    case 'shared':
      return isFromJSON ? rates.shared : convertLHAToMonthly(rates.shared)
    case 1:
      return isFromJSON ? rates['1bed'] : convertLHAToMonthly(rates['1bed'])
    case 2:
      return isFromJSON ? rates['2bed'] : convertLHAToMonthly(rates['2bed'])
    case 3:
      return isFromJSON ? rates['3bed'] : convertLHAToMonthly(rates['3bed'])
    case 4:
      return isFromJSON ? rates['4bed'] : convertLHAToMonthly(rates['4bed'])
    default:
      return isFromJSON ? rates['1bed'] : convertLHAToMonthly(rates['1bed']) // Default to 1 bedroom rate
  }
}

// Get all LHA rates for a specific BRMA
export const getAllLHARates = (brma: any) => {
  const rates: any = (lhaRatesData as any)[brma] || (lhaRates2025_26 as any)[brma] || lhaRates2025_26['Default']

  // Rates from JSON file are already monthly amounts from GOV.UK CSV data
  // No conversion needed
  return {
    sharedRate: rates.shared,
    oneBedRate: rates['1bed'],
    twoBedRate: rates['2bed'],
    threeBedRate: rates['3bed'],
    fourBedRate: rates['4bed'],
  }
}

// Convert weekly LHA rate to monthly
export const convertLHAToMonthly = (weeklyRate: any) => {
  // Note: The LHA rates in our JSON data are already monthly rates
  // This function is kept for compatibility but should not multiply by 4.33
  return weeklyRate // Rates are already monthly
}

// Get bedroom entitlement description
export const getBedroomEntitlementDescription = (bedroomEntitlement: any) => {
  switch (bedroomEntitlement) {
    case 'shared':
      return 'Shared Accommodation Rate (SAR) - for single people under 35'
    case 1:
      return '1 bedroom - for single people 35+ or couples'
    case 2:
      return '2 bedrooms - includes space for children'
    case 3:
      return '3 bedrooms - includes space for children'
    case 4:
      return '4 bedrooms - maximum entitlement'
    default:
      return '1 bedroom - standard entitlement'
  }
}

// Calculate housing element based on LHA
export const calculateHousingElement = (
  brma: any,
  bedroomEntitlement: any,
  actualRent: any,
  serviceCharges = 0
) => {
  const weeklyLHARate = getLHARate(brma, bedroomEntitlement)
  const monthlyLHARate = convertLHAToMonthly(weeklyLHARate)

  // Housing element is the lower of: actual rent or LHA rate
  const eligibleRent = Math.min(actualRent, monthlyLHARate)

  // Add service charges if they're eligible
  const totalHousingElement = eligibleRent + serviceCharges

  return {
    weeklyLHARate,
    monthlyLHARate,
    actualRent,
    eligibleRent,
    serviceCharges,
    totalHousingElement,
    shortfall: Math.max(0, actualRent - monthlyLHARate),
  }
}
