// Local Housing Allowance (LHA) Data Service
// Based on government statistics: https://www.gov.uk/government/statistics/local-housing-allowance-indicative-rates-for-2024-to-2025

let brmaListEngland: any = []
let brmaListScotland: any = []
let brmaListWales: any = []
let lhaRatesData: any = {}

try {
  // This file is generated by scripts/build-brma-list
  // and contains an array of BRMA names (strings) for England.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = await import('../../../data/brmaListEngland.json')
  brmaListEngland = mod.default ?? mod
} catch (e) {
  brmaListEngland = []
}

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = await import('../../../data/brmaListScotland.json')
  brmaListScotland = mod.default ?? mod
} catch (e) {
  brmaListScotland = []
}

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = await import('../../../data/brmaListWales.json')
  brmaListWales = mod.default ?? mod
} catch (e) {
  brmaListWales = []
}

try {
  // This file is generated by scripts/fetch-lha-data
  // and contains the real LHA rates for 2025-2026.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const mod = await import('../../../data/lhaRates2025_26.json')
  lhaRatesData = mod.default ?? mod
} catch (e) {
  lhaRatesData = {}
}

// Fallback LHA rates - only used if lhaRates2025_26.json fails to load
// Real rates are in src/data/lhaRates2025_26.json sourced from:
// https://www.gov.uk/government/publications/universal-credit-local-housing-allowance-rates-2025-to-2026
export const lhaRates2025_26: Record<string, Record<string, number>> = {
  Default: { shared: 400.0, '1bed': 600.0, '2bed': 750.0, '3bed': 900.0, '4bed': 1200.0 },
}

// Keep the old rates for backward compatibility
export const lhaRates2024_25 = lhaRates2025_26

// Get all available BRMA names for dropdown (legacy - returns all combined)
export const getBRMANames = (): any => {
  if (Array.isArray(brmaListEngland) && brmaListEngland.length > 0) {
    return brmaListEngland
  }
  return Object.keys(lhaRates2024_25)
}

// Get grouped BRMAs by country
export const getGroupedBRMAs = (): any => {
  const groups = []

  if (Array.isArray(brmaListEngland) && brmaListEngland.length > 0) {
    groups.push({
      label: 'England',
      options: brmaListEngland,
    })
  }

  if (Array.isArray(brmaListScotland) && brmaListScotland.length > 0) {
    groups.push({
      label: 'Scotland',
      options: brmaListScotland,
    })
  }

  if (Array.isArray(brmaListWales) && brmaListWales.length > 0) {
    groups.push({
      label: 'Wales',
      options: brmaListWales,
    })
  }

  return groups
}

// Calculate bedroom entitlement based on circumstances
export const calculateBedroomEntitlement = (
  circumstances: any,
  age: any,
  _partnerAge: any,
  children: any,
  childAges: any,
  childGenders: any
) => {
  let entitlement = 0

  // Single person under 35 gets shared accommodation rate
  if (circumstances === 'single' && age < 35) {
    return 'shared'
  }

  // Single person 35+ or couple gets 1 bedroom
  if (circumstances === 'single' && age >= 35) {
    entitlement = 1
  } else if (circumstances === 'couple') {
    entitlement = 1
  }

  // Add bedrooms for children
  if (children > 0) {
    // Children under 10 of same gender share a room
    // Children under 16 of opposite gender need separate rooms
    let childBedrooms = 0
    let boysUnder10 = 0
    let girlsUnder10 = 0
    let children10to15 = 0

    childAges.forEach((childAge: any, index: any) => {
      if (childAge < 10) {
        if (childGenders[index] === 'male') boysUnder10++
        else girlsUnder10++
      } else if (childAge < 16) {
        children10to15++
      }
    })

    // Calculate bedrooms needed for children
    childBedrooms += Math.ceil(boysUnder10 / 2) // Boys under 10 can share
    childBedrooms += Math.ceil(girlsUnder10 / 2) // Girls under 10 can share
    childBedrooms += children10to15 // Children 10-15 need separate rooms

    entitlement += childBedrooms
  }

  // Cap at 4 bedrooms (maximum LHA rate)
  return Math.min(entitlement, 4)
}

// Get LHA rate for a specific BRMA and bedroom entitlement
export const getLHARate = (brma: any, bedroomEntitlement: any) => {
  // Use real data from JSON file if available, otherwise fall back to hardcoded rates
  const rates: any =
    (lhaRatesData as any)[brma] ||
    (lhaRates2025_26 as any)[brma] ||
    (lhaRates2025_26 as any)['Default']

  // Rates from JSON file are already monthly amounts from GOV.UK CSV data
  // For hardcoded rates (fallback), convert from weekly to monthly
  const isFromJSON = (lhaRatesData as any)[brma]

  switch (bedroomEntitlement) {
    case 'shared':
      return isFromJSON ? rates.shared : convertLHAToMonthly(rates.shared)
    case 1:
      return isFromJSON ? rates['1bed'] : convertLHAToMonthly(rates['1bed'])
    case 2:
      return isFromJSON ? rates['2bed'] : convertLHAToMonthly(rates['2bed'])
    case 3:
      return isFromJSON ? rates['3bed'] : convertLHAToMonthly(rates['3bed'])
    case 4:
      return isFromJSON ? rates['4bed'] : convertLHAToMonthly(rates['4bed'])
    default:
      return isFromJSON ? rates['1bed'] : convertLHAToMonthly(rates['1bed']) // Default to 1 bedroom rate
  }
}

// Get all LHA rates for a specific BRMA
export const getAllLHARates = (brma: any) => {
  const rates: any =
    (lhaRatesData as any)[brma] ||
    (lhaRates2025_26 as any)[brma] ||
    (lhaRates2025_26 as any)['Default']

  // Rates from JSON file are already monthly amounts from GOV.UK CSV data
  // No conversion needed
  return {
    sharedRate: rates.shared,
    oneBedRate: rates['1bed'],
    twoBedRate: rates['2bed'],
    threeBedRate: rates['3bed'],
    fourBedRate: rates['4bed'],
  }
}

// Convert weekly LHA rate to monthly
export const convertLHAToMonthly = (weeklyRate: any) => {
  // Note: The LHA rates in our JSON data are already monthly rates
  // This function is kept for compatibility but should not multiply by 4.33
  return weeklyRate // Rates are already monthly
}

// Get bedroom entitlement description
export const getBedroomEntitlementDescription = (bedroomEntitlement: any) => {
  switch (bedroomEntitlement) {
    case 'shared':
      return 'Shared Accommodation Rate (SAR) - for single people under 35'
    case 1:
      return '1 bedroom - for single people 35+ or couples'
    case 2:
      return '2 bedrooms - includes space for children'
    case 3:
      return '3 bedrooms - includes space for children'
    case 4:
      return '4 bedrooms - maximum entitlement'
    default:
      return '1 bedroom - standard entitlement'
  }
}

// Calculate housing element based on LHA
export const calculateHousingElement = (
  brma: any,
  bedroomEntitlement: any,
  actualRent: any,
  serviceCharges: any = 0
) => {
  const weeklyLHARate = getLHARate(brma, bedroomEntitlement)
  const monthlyLHARate = convertLHAToMonthly(weeklyLHARate)

  // Housing element is the lower of: actual rent or LHA rate
  const eligibleRent = Math.min(actualRent, monthlyLHARate)

  // Add service charges if they're eligible
  const totalHousingElement = eligibleRent + serviceCharges

  return {
    weeklyLHARate,
    monthlyLHARate,
    actualRent,
    eligibleRent,
    serviceCharges,
    totalHousingElement,
    shortfall: Math.max(0, actualRent - monthlyLHARate),
  }
}
