/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BenefitsCalculatorRouteRouteImport } from './routes/benefits-calculator/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenefitsCalculatorSlugRouteImport } from './routes/benefits-calculator/$slug'

const BenefitsCalculatorRouteRoute = BenefitsCalculatorRouteRouteImport.update({
  id: '/benefits-calculator',
  path: '/benefits-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsCalculatorSlugRoute = BenefitsCalculatorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BenefitsCalculatorRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benefits-calculator': typeof BenefitsCalculatorRouteRouteWithChildren
  '/benefits-calculator/$slug': typeof BenefitsCalculatorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benefits-calculator': typeof BenefitsCalculatorRouteRouteWithChildren
  '/benefits-calculator/$slug': typeof BenefitsCalculatorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benefits-calculator': typeof BenefitsCalculatorRouteRouteWithChildren
  '/benefits-calculator/$slug': typeof BenefitsCalculatorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benefits-calculator' | '/benefits-calculator/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benefits-calculator' | '/benefits-calculator/$slug'
  id: '__root__' | '/' | '/benefits-calculator' | '/benefits-calculator/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenefitsCalculatorRouteRoute: typeof BenefitsCalculatorRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/benefits-calculator': {
      id: '/benefits-calculator'
      path: '/benefits-calculator'
      fullPath: '/benefits-calculator'
      preLoaderRoute: typeof BenefitsCalculatorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits-calculator/$slug': {
      id: '/benefits-calculator/$slug'
      path: '/$slug'
      fullPath: '/benefits-calculator/$slug'
      preLoaderRoute: typeof BenefitsCalculatorSlugRouteImport
      parentRoute: typeof BenefitsCalculatorRouteRoute
    }
  }
}

interface BenefitsCalculatorRouteRouteChildren {
  BenefitsCalculatorSlugRoute: typeof BenefitsCalculatorSlugRoute
}

const BenefitsCalculatorRouteRouteChildren: BenefitsCalculatorRouteRouteChildren =
  {
    BenefitsCalculatorSlugRoute: BenefitsCalculatorSlugRoute,
  }

const BenefitsCalculatorRouteRouteWithChildren =
  BenefitsCalculatorRouteRoute._addFileChildren(
    BenefitsCalculatorRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenefitsCalculatorRouteRoute: BenefitsCalculatorRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
