/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfEmploymentAccountsRouteImport } from './routes/self-employment-accounts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BenefitRatesRouteImport } from './routes/benefit-rates'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorIdRouteRouteImport } from './routes/calculator.$id/route'
import { Route as CalculatorIdSlugRouteImport } from './routes/calculator.$id/$slug'

const SelfEmploymentAccountsRoute = SelfEmploymentAccountsRouteImport.update({
  id: '/self-employment-accounts',
  path: '/self-employment-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitRatesRoute = BenefitRatesRouteImport.update({
  id: '/benefit-rates',
  path: '/benefit-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIdRouteRoute = CalculatorIdRouteRouteImport.update({
  id: '/calculator/$id',
  path: '/calculator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorIdSlugRoute = CalculatorIdSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CalculatorIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/benefit-rates': typeof BenefitRatesRoute
  '/login': typeof LoginRoute
  '/self-employment-accounts': typeof SelfEmploymentAccountsRoute
  '/calculator/$id': typeof CalculatorIdRouteRouteWithChildren
  '/calculator/$id/$slug': typeof CalculatorIdSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/benefit-rates': typeof BenefitRatesRoute
  '/login': typeof LoginRoute
  '/self-employment-accounts': typeof SelfEmploymentAccountsRoute
  '/calculator/$id': typeof CalculatorIdRouteRouteWithChildren
  '/calculator/$id/$slug': typeof CalculatorIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/benefit-rates': typeof BenefitRatesRoute
  '/login': typeof LoginRoute
  '/self-employment-accounts': typeof SelfEmploymentAccountsRoute
  '/calculator/$id': typeof CalculatorIdRouteRouteWithChildren
  '/calculator/$id/$slug': typeof CalculatorIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/benefit-rates'
    | '/login'
    | '/self-employment-accounts'
    | '/calculator/$id'
    | '/calculator/$id/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/benefit-rates'
    | '/login'
    | '/self-employment-accounts'
    | '/calculator/$id'
    | '/calculator/$id/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/benefit-rates'
    | '/login'
    | '/self-employment-accounts'
    | '/calculator/$id'
    | '/calculator/$id/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BenefitRatesRoute: typeof BenefitRatesRoute
  LoginRoute: typeof LoginRoute
  SelfEmploymentAccountsRoute: typeof SelfEmploymentAccountsRoute
  CalculatorIdRouteRoute: typeof CalculatorIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-employment-accounts': {
      id: '/self-employment-accounts'
      path: '/self-employment-accounts'
      fullPath: '/self-employment-accounts'
      preLoaderRoute: typeof SelfEmploymentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefit-rates': {
      id: '/benefit-rates'
      path: '/benefit-rates'
      fullPath: '/benefit-rates'
      preLoaderRoute: typeof BenefitRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/$id': {
      id: '/calculator/$id'
      path: '/calculator/$id'
      fullPath: '/calculator/$id'
      preLoaderRoute: typeof CalculatorIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator/$id/$slug': {
      id: '/calculator/$id/$slug'
      path: '/$slug'
      fullPath: '/calculator/$id/$slug'
      preLoaderRoute: typeof CalculatorIdSlugRouteImport
      parentRoute: typeof CalculatorIdRouteRoute
    }
  }
}

interface CalculatorIdRouteRouteChildren {
  CalculatorIdSlugRoute: typeof CalculatorIdSlugRoute
}

const CalculatorIdRouteRouteChildren: CalculatorIdRouteRouteChildren = {
  CalculatorIdSlugRoute: CalculatorIdSlugRoute,
}

const CalculatorIdRouteRouteWithChildren =
  CalculatorIdRouteRoute._addFileChildren(CalculatorIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BenefitRatesRoute: BenefitRatesRoute,
  LoginRoute: LoginRoute,
  SelfEmploymentAccountsRoute: SelfEmploymentAccountsRoute,
  CalculatorIdRouteRoute: CalculatorIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
